In [3]:
import sys
import numpy as np

Arrays and Indexing

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
a = np.array([1,2,3,4])

In [7]:
b = np.array([0, -5, 1, 1.5, 2])

In [6]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [10]:
b[[0, 2, -1]]

array([0., 1., 2.])

Array Types

In [11]:
a.dtype

dtype('int32')

Dimensions and Shapes

In [13]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [14]:
A.shape

(2, 3)

In [15]:
A.ndim

2

In [16]:
A.size

6

Indexing and Slicing of Matrices

In [18]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [19]:
A[1]

array([4, 5, 6])

In [20]:
A[1][0]

4

In [23]:
A[1,0]

4

In [22]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [25]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [26]:
A[1] = np.array([10, 10, 10])

In [27]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [28]:
A[2] = 99

In [29]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

Quiz

In [17]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


Summary Statistics

In [30]:
a = np.array([1,2,3,4])

In [31]:
a.sum()

10

In [32]:
a.mean()

2.5

In [33]:
a.std()

1.118033988749895

In [34]:
a.var()

1.25

In [35]:
a.sum(axis=0)

10

In [36]:
a.min()

1

In [37]:
a.max()

4

In [38]:
a.mean()

2.5

Numpy Operations

Broadcasting and Vectorized Operations

In [41]:
a = np.arange(4)

In [42]:
a

array([0, 1, 2, 3])

In [43]:
a + 10

array([10, 11, 12, 13])

In [44]:
a * 10

array([ 0, 10, 20, 30])

In [47]:
a += 100
a

array([200, 201, 202, 203])

In [48]:
l = [0,1,2,3]
[i * 10 for i in l]

[0, 10, 20, 30]

Quiz

In [39]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

Boolean Arrays

In [5]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [6]:
a[[0, -1]]

array([0, 3])

In [7]:
a[[True, False, False, True]]

array([0, 3])

In [8]:
a >= 2

array([False, False,  True,  True])

In [9]:
a[a >= 2]

array([2, 3])

In [10]:
a.mean()

1.5

In [11]:
a[a > a.mean()]

array([2, 3])

In [12]:
a[~(a > a.mean())]
# all the elements that are not greater than the mean

array([0, 1])

In [13]:
a[(a == 0) | (a == 1)]

array([0, 1])

Quiz

In [53]:
a = np.arange(5)
print(a <= 3)

[ True  True  True  True False]


Numpy Algebra and Size